add linting and static analysis

diff --git a/.github/workflows/java-build-test.yml b/.github/workflows/java-build-test.yml
--- a/.github/workflows/java-build-test.yml
+++ b/.github/workflows/java-build-test.yml
@@ -19,13 +19,32 @@ jobs:
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Test
+      - name: Spotless Format Check
+        id: spotless
+        continue-on-error: true
         working-directory: ./booking-service-java
-        run: mvn test  # Allows for tests when we make them
+        run: mvn spotless:check
+
+      - name: SpotBugs Check
+        id: spotbugs
+        continue-on-error: true
+        working-directory: ./booking-service-java
+        run: mvn spotbugs:check
 
       - name: Build
+        id: build
+        continue-on-error: true
         working-directory: ./booking-service-java
-        run: mvn clean package -DskipTests
+        # Runs tests, compilation, integrated plugins
+        run: mvn clean verify
+
+      - name: Stop on Failure
+        if: steps.spotless.outcome == 'failure' ||
+          steps.spotbugs.outcome == 'failure' ||
+          steps.build.outcome == 'failure'
+        run: |
+          echo "One or multiple steps failed, exiting."
+          exit 1
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v7
diff --git a/.github/workflows/node-build-test.yml b/.github/workflows/node-build-test.yml
--- a/.github/workflows/node-build-test.yml
+++ b/.github/workflows/node-build-test.yml
@@ -28,10 +28,49 @@ jobs:
           cache: 'npm'
           cache-dependency-path: './package-lock.json'
 
-      - name: Install & Test
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Security Audit
+        id: sec
+        continue-on-error: true
+        run: npm audit --audit-level=high
+
+      - name: Check Formatting (Prettier)
+        id: form
+        continue-on-error: true
+        run: npx prettier --check .
+
+      - name: Lint (ESLint)
+        id: lint
+        continue-on-error: true
+        run: npx eslint .
+
+      - name: Type Check
+        id: type
+        continue-on-error: true
+        run: npm run type-check
+
+      - name: Validate ASL
+        id: asl
+        continue-on-error: true
+        run: npm run asl-validate
+
+      - name: Test
+        id: test
+        continue-on-error: true
+        run: npm test --workspace=${{ inputs.working_directory }}
+
+      - name: Stop on Failure
+        if: steps.sec.outcome == 'failure' ||
+            steps.form.outcome == 'failure' ||
+            steps.lint.outcome == 'failure' ||
+            steps.type.outcome == 'failure' ||
+            steps.asl.outcome == 'failure' ||
+            steps.test.outcome == 'failure'
         run: |
-          npm ci
-          npm test --workspace=${{ inputs.working_directory }}
+          echo "One or multiple steps failed, exiting."
+          exit 1
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v7
